version: '5.6'
services:
  Mysql:
    container_name: mysql    #Container name in docker
    image: mysql
    ports:
      - '3307:3306'          #Use port 3307 to allow port 3306 to be free
    volumes:
      - ../../databases/sql-data/db:/var/lib/mysql    #route where database is going to be stored
    hostname: localhost
    environment:
      MYSQL_DATABASE: 'bdmysql'       #Database name in MySQL
      MYSQL_ROOT_PASSWORD: 'root'     #Password in MySQL


  